name: "Custom Secret Scanning"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  secret-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run custom secret scanning
        uses: github/secret-scanning-action@v1
        with:
          config-file: .github/secret-scanning-config.yml
